### ISSUE TITLE
New release w/updates

### ISSUE THREAD

**Issue by maxzinkus** [beringresearch/macpine#102]
What do you think a good cutoff for `0.10` would be? Alternatively, do you think we could go `1.0b` (beta) given the new features and testing?

Related: [my PR on homebrew-core](https://github.com/Homebrew/homebrew-core/pull/126108) to add completions as part of `brew install macpine`.

The TODO for this would be a new GH tagged release, plus a `brew bump-formula-pr` version bump PR to https://github.com/Homebrew/homebrew-core

**Comment by maxzinkus** [comment]
@idroz this one is entirely up to your discretion.

**Comment by idroz** [comment]
I've been thinking about a new release.

I think current big fixes and features warrant a 0.91 version bump.

For 1.0 (b), need to think if features being tested #104 and #96 carry a risk of being not backwards compatible. If so, it would make sense to introduce them pre 1.0, I think.
