### ISSUE TITLE
Remove OS header from `alpine list`

### ISSUE THREAD

**Issue by idroz** [beringresearch/macpine#110]
My initial idea was to have a general lightweight linux VM system, but I think focusing on Alpine is the way to go, particularly ,since we can easily run containers inside an Alpine VM that enable access to other linux OSs.

The proposed output would be:

```bash
NAME               STATUS      SSH    PORTS ARCH     PID          TAGS                
cheerful-result    Running     25           aarch64  26568                         
glittering-swing   Running     23           x86_64   57206        emulation,intel
```

It would also free up some space for a longer list of tags

**Comment by maxzinkus** [comment]
We can leave the documentation that references other Linuxes, and leave it as an unsupported power-user "feature" that they can hack the config under the hood to make other OSes run. Sounds good!
