### ISSUE TITLE
Add a maintainer?

### ISSUE THREAD

**Issue by maxzinkus** [beringresearch/macpine#113]
@idroz :)

I've found this software very useful in my research and my work in the past few months, and have been happy to have a chance to provide contributions, answer questions people have in issues, and work on the project. I foresee that I'll use this software for a long time to come.

Do you think I could be added as a maintainer on the project? You'd still have principal & overriding permissions as the repo owner, and we could even enable branch protection and required reviews if you'd like to healthily mistrust my contributions ☺️

I've always enjoyed open source projects but haven't previously gotten to be involved as much as I have here, and would love to be brought into the fold.

Thanks for your efforts, for sharing this project with the world, and for always reviewing my code 😂

**Comment by idroz** [comment]
@maxzinkus your contributions have been superb! I'm really glad you found this project, no reservations at all and will be adding you as a maintainer shortly.
