### ISSUE TITLE
Autostart VM on publish/import

### ISSUE THREAD

**Issue by idroz** [beringresearch/macpine#136]
Testing the new publish/import features - looking very slick.

I'm wondering whether we should autostart the VM on publish/import as at the moment the VM status is STOPPED.

**Comment by idroz** [comment]
For example, it would make sense to start the VM back up on `publish`, but can see a rationalle for keeping it STOPPED on `import`.

**Comment by maxzinkus** [comment]
I agree, I think the minimum change should occur as often as possible:
- stopped should stay stopped
- running can be paused, published, and unpaused
- paused should stay paused

But, for pausing, we should probably do something like `machineConfig.Exec("sync && sleep 3" , true)` before pausing

**Comment by maxzinkus** [comment]
Awesome, thank you!!
