### ISSUE TITLE
Round up tasks for 0.11 / 1.0

### ISSUE THREAD

**Issue by maxzinkus** [beringresearch/macpine#139]
If there's anything else to be done? Documentation, examples, etc?

**Comment by maxzinkus** [comment]
Our wonderful users (whomsoever they may be) don't yet get to enjoy things like `pause`, `publish --encrypt`, and other QoL changes we've made recently.

I don't foresee any significant API changes in the near future -- if you don't either, maybe we can wrap it all up into a new release!

**Comment by idroz** [comment]
I don’t think there’s anything outstanding.

we do need docs, tests, access to new alpine vm versions, but that shouldn’t affect the user experience.

I think we can go for a 1.0 release. The only point I need to clarify is how brew is handling version tags? V1.00 should be ok?

**Comment by maxzinkus** [comment]
As seen in the [`livecheck regex`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/macpine.rb), Homebrew looks for tags of the form:

```/^v?\.?(\d+(?:\.\d+)*)$/i```

That is:
- literal 'v'
- optional '.'
- one or more decimal digits
- optionally, one or more '.' and sets of digits repeatedly
- case-insensitive

So tags can be e.g.:
- `v.01`
- `v0.1`
- `V1`
- `v1.0`
- `v.0.1`
- `v1.0.0.0`

**Comment by idroz** [comment]
Nice - will release 1.0 now and will aim to do a little bit of propagation through HN/reddit towards the end of the week .
