### ISSUE TITLE
Automating the release process

### ISSUE THREAD

**Issue by maxzinkus** [beringresearch/macpine#141]
`utils/utils.go` should now once again be cross-platform supported.

When you get a chance, can you regenerate `v1.0` or otherwise make a new `v1.0.1` so I can get it sync'd into the Homebrew formula? Thanks!

Also, if it sounds convenient we can make a Github Action to build the `amd64` and `aarch64` binaries and generate a release whenever a tag is pushed to the repo:
- https://github.com/marvinpinto/action-automatic-releases
- https://github.com/softprops/action-gh-release

If you could reply with the commands you run to cross-compile etc when generating a release, I can put them into a new action.

That way we can both trigger the release process :) by simply doing:

```bash
git tag v1.1
git push
```

**Comment by idroz** [comment]
New release pushed - thanks, @maxzinkus 

I use github.com/mitchellh/gox@v1.0.1 tool to cross compile and execute `xcompile.sh` script to get amd64/arm64 binaries.

**Comment by maxzinkus** [comment]
Awesome. I figured, just wasn't sure if there were any other steps :)

**Comment by maxzinkus** [comment]
@idroz 1.0.1 is live!

**Comment by maxzinkus** [comment]
@idroz if you're good with it, I'll look at integrating a release Action? It may require a GitHub API token at some point, I'll let you know

**Comment by maxzinkus** [comment]
@idroz I added `release.yml`. Can you [add a (classic) Github token](https://github.com/settings/tokens) with the `public_repo` permission set and add it to the `secrets` for this repository with the name `PUBLIC_RW_TOKEN`?

**Comment by maxzinkus** [comment]
<img width="794" alt="Screenshot 2023-04-27 at 3 00 14 PM" src="https://user-images.githubusercontent.com/5474655/234977503-649d6cc1-3b9b-4f97-9a2f-bbf87fc37829.png">

Should look something like ^

**Comment by maxzinkus** [comment]
Then, I'll create v1.0.2 which pushes out the bugfix in `alpine tag` where you can't currently add tags with `-` (which prevents `launchctl-autostart` from being used! whoops)

**Comment by idroz** [comment]
@maxzinkus - new secret with the name `PUBLIC_RW_TOKEN` added

**Comment by maxzinkus** [comment]
Awesome! Looks like everything is working. To create releases:

```bash
git tag v1.0.2
git push --tags
```

Then the tag is created and pushed, [the action runs](https://github.com/beringresearch/macpine/actions/runs/4830089633) and triggers [a release](https://github.com/beringresearch/macpine/releases/tag/v1.0.2) and a [Homebrew PR](https://github.com/Homebrew/homebrew-core/pull/129619) to the macpine formula

**Comment by maxzinkus** [comment]
@idroz @ you so that you see the new release creation steps above ^

**Comment by idroz** [comment]
Nice - this is super helpful - not sure why haven't done it in the past!
