### ISSUE TITLE
[Feature] `alpine import -u/--url` import via URL

### ISSUE THREAD

**Issue by maxzinkus** [beringresearch/macpine#145]
First steps of #144 

- Simplify launch by removing download functionality
- Add `-u / --url` to import (with confirmation `[y/N]` about safety of imported instances, perhaps with a -y option to bypass the confirmation)
- Remove `.qcow2` files and replace with pre-built and `publish`'d instances

**Comment by idroz** [comment]
Addressed in #188 

Remote and local images can be imported using the same syntax:

`alpine import /path/to/local/image.tar.gz` or `alpine import https://path/to/remote/image.tar.gz`

A special case is implemented to handle direct Dropbox links.
