### ISSUE TITLE
[Bug] GH Action release.yml Personal Access Token requires `workflow` scope

### ISSUE THREAD

**Issue by maxzinkus** [beringresearch/macpine#150]
`bump-macpine-1.0.3 -> bump-macpine-1.0.3 (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/automerge.yml` without `workflow` scope)`

Need to edit the personal access token in the repo secrets to have the `workflow` scope to continue to be allowed to open PRs on `homebrew-core`

**Comment by maxzinkus** [comment]
May require a new token to be created with the appropriate scopes. Once it's in place, we can re-run the release.yml action to recreate v1.0.3 and the homebrew update PR

**Comment by beringresearch** [comment]
I've been having issues with GitHub today. Will try creating a new token and see if it fixes that.

**Comment by idroz** [comment]
Token updated - hopefully will work?
