### ISSUE TITLE
[Feature] Improve verbosity of macpine instance logs to help troubleshoot failed instances

### ISSUE THREAD

**Issue by idroz** [beringresearch/macpine#156]
Not necessarily a macpine thing, but have encountered cases where boot loader fails without a clear error. The only way of debugging is running macpine disk image through emu itself.

**Comment by maxzinkus** [comment]
I've kind of been thinking for a while that we should have `-v` and `-vv` verbosity levels. At default, maybe we only print errors but not informational messages, at level 1 we print like we currently do, and level 2 adds all the debugging output.

What are your thoughts?

**Comment by maxzinkus** [comment]
That said, I haven't found any similar issues with bootloaders, but I've also only used the default alpine3.16 build.

**Comment by maxzinkus** [comment]
Tagging this one to you as you have experience with the issue at hand, but obviously it's a whenever-you-have-time :)

**Comment by idroz** [comment]
No hard requirements at this stage, so closing as wontfix. Can revisit in the future
