### ISSUE TITLE
[Bug] fail to list/start vms after `alpine rename` of a stopped instance

### ISSUE THREAD

**Issue by idroz** [beringresearch/macpine#157]
**Describe the bug**
as above

**To Reproduce**
1. alpine launch --image alpine_3.16.0 --name amd64 --arch x86_64 -s 23
2. alpine stop amd64
3. alpine rename amd64 test
4. alpine start or alpine list

Will produce 2023/05/10 12:36:02 error checking status of qemu process: exit status 1

**Expected behavior**
Should be able to rename a stopped VM without any side effects

**Comment by maxzinkus** [comment]
Weird, I haven't encountered this. Thank you!
