### ISSUE TITLE
[Bug] alpine_3.19.1 is gone, replaced with inaccessible alpine_3.18.6?

### ISSUE THREAD

**Issue by joshuahhh** [beringresearch/macpine#190]
Launching a vm with image "alpine_3.19.1" gives the error:
```
2024/07/24 21:17:46 unable to download alpine_3.19.1-aarch64.qcow2 for aarch64: requested image download is not supported: StatusCode 404
```

I believe this is because the image has been removed from the v.01 release:
 
![Screenshot 2024-07-24 at 9 22 42 PM](https://github.com/user-attachments/assets/f5fe3acf-b642-4c7d-aca6-0759ad1b214b)

It looks like it's been replaced with alpine_3.18.6, but when I try to use that, I get the error:
```
2024/07/24 21:23:41 unsupported image. only -i alpine_3.16.0 | alpine_3.19.1 | debian_11.3.0 are currently available
```

So neither of these are available.

**Comment by idroz** [comment]
Hi - thanks for this. There seem to be an ongoing issue with alpine versions > 3.16 that prevents VMs being accessed in vmnet-shared networking mode. This is due to changes in alpine itself. Manual upgrade to 3.18 seems to work (although 3.19 doesn't), but the image that alpine provides does not.
