### ISSUE TITLE
[Bug] Alpine import fails if ~/.macpine doesn't exists

### ISSUE THREAD

**Issue by paulrouget** [beringresearch/macpine#191]
- Export file is `$HOME/xxx.tar.gz`
- I do not have `$HOME/.macpine` directory yet (I migrated from an old machine to a new one)
- in my home directory I do `alpine import ./xxx.tar.gz`
- `unable to import: open /Users/xxx/.macpine/xxx.tar.gz: no such file or directory`
- mkdir `.macpine`
- now import works

**Comment by idroz** [comment]
Nice spot!

I pushed a quick fix into the main branch - let me know if that solves the issue.

**Comment by paulrouget** [comment]
That does it! Thank you :)
