### ISSUE TITLE
[Feature] Add x86_64 3.20.3 image to the project

### ISSUE THREAD

**Issue by rauhryan** [beringresearch/macpine#202]
**Is your feature request related to a problem? Please describe.**
Installing from source does not support x86_64 because there is no x86_64 image in the https://github.com/beringresearch/macpine/releases/tag/v.01 for x86_64. I was able to build one from an alpine image

```bash
qemu-img create -f qcow2 alpine_3.20.3-x86_64.qcow2 1G 

wget https://dl-cdn.alpinelinux.org/alpine/v3.16/releases/x86_64/alpine-standard-3.20.3-x86_64.iso

qemu-system-x86_64 -cpu qemu64 -m 1G \
    -hda alpine_3.20.3-x86_64.qcow2 \
    -cdrom alpine-standard-3.20.3-x86_64.iso \
    -boot d \
    -smp 2 \
    -netdev user,id=net0,hostfwd=tcp::3024-:22 \
    -device e1000,netdev=net0,mac=56:c9:81:7f:9c:0b

# inside the vm run alpine-setup
# Allow root ssh login: yes
# Which disk you would like to use: sda
# How would you like to use it: sys
```

However is still doesn't work as the cli will error when it tries to download the image from github.
I was able to work around this

```
cp alpine_3.20.3-x86_64.qcow2 ~/.macpine/cache
```

After this I was able to alpine to happily work with a new template virtual disk that is 3.20.3

I could contribute the qcow2 file that I've built, but I'm not sure how to share it with you, let me know if you are interested

**Describe the solution you'd like**

I would be great to have the ability to just define a qcow2 file that I have on disk as an image

Let me know your thoughts, thanks for the project, really enjoying it so far

**Comment by idroz** [comment]
-Amazing! All alpine qcows are in release assets here: https://github.com/beringresearch/macpine/releases/tag/v.01

this is where machine looks for a disk image if it’s not in cache. I’ll see if I can make you a contributor to the project, in which case you can upload the qcow directly into the release.

**Comment by idroz** [comment]
@rauhryan just added you as collaborator. You should be able to edit the release and upload the x86 alpine qcow into it: https://github.com/beringresearch/macpine/releases/tag/v.01

**Comment by rauhryan** [comment]
<img width="1251" alt="Release_v_01_·_beringresearch_macpine" src="https://github.com/user-attachments/assets/ff7966ea-9fbc-4a23-be22-0fabaafcecc8">

Done!

**Comment by chadwagoner** [comment]
Don't know if this is 'approved' or what not.. But this is how I used more recent releases with this tool..

```
alpine exec <name> 'echo -e "### CONTROLLED BY PDC\n\nhttp://dl-cdn.alpinelinux.org/alpine/v3.21/main\nhttp://dl-cdn.alpinelinux.org/alpine/v3.21/community" > /etc/apk/repositories && apk upgrade -U && apk add -U bash chrony curl && rc-update add chronyd && service chronyd start && grub-install --target=arm64-efi --efi-directory=/boot/efi --bootloader-id=alpine --boot-directory=/boot --no-nvram && install -D /boot/efi/EFI/alpine/grubaa64.efi /boot/efi/EFI/boot/bootaa64.efi && reboot' && \
sleep 20 && \
alpine ssh <name>
```

I can't remember where I found these grub commands and what not, but it essentially fixes the grub problem and allows you to use any version.. So I typically just start a new instance with default, then upgrade it to whatever version I want using this set of commands and haven't had any issues.. 

Figured I'd share
