### ISSUE TITLE
Unable to use alpine command

### ISSUE THREAD

**Issue by shepherd1530** [beringresearch/macpine#30]
I am unable to use none of the alpine commands after successful installation. I get the below error.

```
sudo: alpine: command not found
```

OS: MacOs 12.6 m1

**Comment by adrozdovbering** [comment]
After downloading the binary with `wget` run the following command to change downloaded file type to executable:
```
chmod +x alpine
```
After this move this file into `/usr/local/bin` as per instructions.

Hope this helps.

**Comment by shepherd1530** [comment]
That fixes it. Thanks.
