### ISSUE TITLE
no formulae lxd

### ISSUE THREAD

**Issue by bunam** [beringresearch/macpine#35]
`➜  macpine git:(main) brew install lxd

Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).

You have 8 outdated formulae and 2 outdated casks installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

Warning: No available formula with the name "lxd". Did you mean lxc or lsd?
==> Searching for similarly named formulae...
These similarly named formulae were found:
lxc ✔                                                               lsd
To install one of them, run (for example):
  brew install lxc ✔
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.`

Where I have missed something ?

**Comment by idroz** [comment]
Oops , my fault -

`brew install lxc`

**Comment by idroz** [comment]
Should be fixed via #36
