### ISSUE TITLE
Mount file permissions issue?

### ISSUE THREAD

**Issue by brandonros** [beringresearch/macpine#44]
```
root@debian:~/mnt/components# cargo build
error: failed to open: /root/mnt/components/target/debug/.cargo-lock
Caused by:
  Permission denied (os error 13)
root@debian:~/mnt/components# ls -lta target/debug/.cargo-lock 
-rw-r--r-- 1 nobody nogroup 0 Nov 27 01:44 target/debug/.cargo-lock
```

Not exactly specific to this repo but... any tips on how to work around it?

**Comment by idroz** [comment]
I've seen this before when UID and GIDs between LXD containers and host don't align, making any mounted directories read-only. 

setting `shift=true` on the disk device being attached could work. See: https://discuss.linuxcontainers.org/t/mount-home-directory-read-only-permission-denied/10241

**Comment by brandonros** [comment]
could this be solved at the alpine -> QEMU -> LXD/LXC layer in this repo automatically or not really?

**Comment by idroz** [comment]
Will look into this. I think it should be possible to map current user if values at vm startup

**Comment by idroz** [comment]
Permissions should be sorted out now using the code in the latest main branch. #50 

9p is used to securely mount a directory between the host and a VM. Inside QEMU VM directory is given read-write access to all users. This doesn't modify directory ownership on the host through 9p configuration.
