### ISSUE TITLE
Request: installation via Homebrew Cask

### ISSUE THREAD

**Issue by nlhomme** [beringresearch/macpine#48]
Hello there,

It's too bad that we have to install macpine and qemu from two different tools (macport and brew).

Can you make it available on [Homebrew Cask](https://github.com/Homebrew/homebrew-cask), or at least give me the autorisation to to it?

Regards

**Comment by idroz** [comment]
Agreed. Don't have much experience with homebrew packaging, so help here would be greatly appreciated.

Do you need to be added as a collaborator to this repo to create a pull request with homebrew cask?

**Comment by caarlos0** [comment]
I'm biased, but you can get that and more with [GoReleaser](https://goreleaser.com)

**Comment by msourabh24** [comment]
Someone has already added macpine as a formulae on Homebrew. May want to test it and then update the installation instructions.

**Comment by idroz** [comment]
[Formula](https://github.com/Homebrew/homebrew-core/pull/116908) added to homebrew by @gpanders

macpine is installable via `brew install macpine`
