### ISSUE TITLE
`alpine stop` does not delete PID file, so `alpine list` reports stopped VM as "Running"

### ISSUE THREAD

**Issue by maxzinkus** [beringresearch/macpine#66]
When running `alpine stop`:

[`cmd/stop.go:24`](https://github.com/beringresearch/macpine/blob/6d473a64aba267f700ee015791a142efc48919d4/cmd/stop.go#L24) calls [`host/stop.go:8`](https://github.com/beringresearch/macpine/blob/6d473a64aba267f700ee015791a142efc48919d4/host/stop.go#L8) which in turn calls [`qemu/ops.go:166`](https://github.com/beringresearch/macpine/blob/6d473a64aba267f700ee015791a142efc48919d4/qemu/ops.go#L166).

However, none of these delete the `alpine.pid` file which they check for. Therefore, the `alpine` CLI displays the status of the stopped incorrectly VM as `Running`.

Easy fix, just delete the file if it exists after a successful `stop` in whichever of these locations makes the most sense. Likely either `qemu/ops.go` or `host/stop.go`.

**Comment by maxzinkus** [comment]
It may also behoove you to add a `-f` "force" stop option which sends `sigkill` instead of `sigterm`.

**Comment by maxzinkus** [comment]
Closing this issue because it stopped happening. I'm not sure why it stopped because nothing in `macpine` is set to delete the PID file. Does `qemu` delete the PID file when the process is `term`d?

**Comment by jdriselvato** [comment]
I'm having this now happen to me. I exited the vm, did `alpine stop simplistic-background` and still see it running 

```
$ alpine list
NAME                      OS         STATUS      SSH    PORTS          ARCH       PID       
simplistic-background     alpine     Running     22     5900,30000     x86_64     63090   
```

The weird thing is, now ssh hangs.

**Comment by maxzinkus** [comment]
This is a qemu thing. `alpine stop` your VMs, `pgrep qemu-system` to make sure none are running, `rm ~/.macpine/simplistic-background/alpine.pid` to clean up the old PIDfile, and you should be good to go.

**Comment by jdriselvato** [comment]
That worked, I'll have to save those commands for later.

alias killalpine="pgrep qemu-system; rm ~/.macpine/simplistic-background/alpine.pid"

Thanks for letting me know.

**Comment by maxzinkus** [comment]
`pgrep string` just lists any running process IDs whose name matches `string`. The important part was the `rm`, and that was specific to your vm name `simplistic-background`. `~/.macpine` contains one folder per VM, each with its name.
