### ISSUE TITLE
Secure credential storage for `config.yaml` 

### ISSUE THREAD

**Issue by maxzinkus** [beringresearch/macpine#70]
I plan to open a PR for this.

It would be useful to allow users to retrieve `SSHUser` credentials from a more secure location than `config.yaml`, especially given that `PermitRootLogin yes` in `/etc/ssh/sshd_config` is required for `alpine start` (among others) to function.

I want to add capabilities for `config.yaml` to be supplemented with environment variables and/or the system credential stores such as `ssh-agent(1)` and `security(1)` (macOS keychains) for added security.

This will allow for robust passwords or even certificate-based ssh without major inconvenience or breakage, and harden VMs that are exposed to incoming network traffic.

**Comment by maxzinkus** [comment]
@idroz you can assign me if this sounds like a good feature. If you think it's out of scope, then you can close it.

**Comment by idroz** [comment]
I think it's a much needed feature.
