### ISSUE TITLE
Help with macpine setup for vnc

### ISSUE THREAD

**Issue by jdriselvato** [beringresearch/macpine#75]
I really appreciate how easy it is to setup an alpine instance. Ideally I want to use macpine to test cross platform GUI development. Here's the steps I've taken thus far:

Launch: 

```
alpine launch -s 22 -p 5900
ssh root@localhost -p 22 #password: root
```

I know my vnc port will be 5900

# Setup

I run the setup tool

```
setup-alpine

apk add vim
```

Note the eth0 address after setup:

```
Configuration for eth0:
  type=static
  address=10.0.2.15
  netmask=255.0.0.0
  gateway=10.0.2.2
```

### Initial setup

Add community repos

```
vim /etc/apk/repositories # add community
apk update

```

### Install Xfce

Docs: https://wiki.alpinelinux.org/wiki/Xfce

#### Install:

```
apk add xfce4 xfce4-terminal xfce4-screensaver lightdm-gtk-greeter dbus

rc-service dbus start
rc-update add dbus

setup-devd udev

```

#### Starting Xfce:

```
rc-service lightdm start
rc-update add lightdm
```

if the above worked (which requires vnc) then:

```
startx
```

### Setup vnc

Install x11vnc

```
apk add x11vnc
```

then run it on display :0

```
$ x11vnc -display :0

(a big warning about) YOU ARE RUNNING X11VNC WITHOUT A PASSWORD!!

26/02/2023 20:33:30 x11vnc version: 0.9.16 lastmod: 2019-01-05  pid: 1844
26/02/2023 20:33:30 Using X display :0
26/02/2023 20:33:30 rootwin: 0x55 reswin: 0x600001 dpy: 0x8f988030

(trimmed some output)

26/02/2023 20:33:30 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120
26/02/2023 20:33:30 
26/02/2023 20:33:30 X display :0 is 32bpp depth=24 true color
26/02/2023 20:33:30 
26/02/2023 20:33:30 Autoprobing TCP port 
26/02/2023 20:33:30 Autoprobing selected TCP port 5900
26/02/2023 20:33:30 Autoprobing TCP6 port 
26/02/2023 20:33:30 Autoprobing selected TCP6 port 5900
26/02/2023 20:33:30 listen6: bind: Address in use
26/02/2023 20:33:30 Not listening on IPv6 interface.

26/02/2023 20:33:30 Xinerama is present and active (e.g. multi-head).
26/02/2023 20:33:30 Xinerama: number of sub-screens: 1
26/02/2023 20:33:30 Xinerama: no blackouts needed (only one sub-screen)
26/02/2023 20:33:30 
26/02/2023 20:33:30 fb read rate: 896 MB/sec
26/02/2023 20:33:30 fast read: reset -wait  ms to: 10
26/02/2023 20:33:30 fast read: reset -defer ms to: 10
26/02/2023 20:33:30 The X server says there are 10 mouse buttons.
26/02/2023 20:33:30 screen setup finished.
26/02/2023 20:33:30 
26/02/2023 20:33:30 WARNING: You are running x11vnc WITHOUT a password.  See
26/02/2023 20:33:30 WARNING: the warning message printed above for more info.
26/02/2023 20:33:30 

The VNC desktop is:      localhost:0
PORT=5900
```

Then on my MacOS: `Finder -> Go -> Connect to Server`

I input `vnc://10.0.2.15:5900`

and it looks like it's trying to connect but then times out:

<img width="598" alt="Screen Shot 2023-02-26 at 20 52 39" src="https://user-images.githubusercontent.com/950825/221453945-010a8710-4b9e-4890-91fc-d0fa8d5a1259.png">

<img width="542" alt="Screen Shot 2023-02-26 at 20 52 46" src="https://user-images.githubusercontent.com/950825/221453961-bbe6da93-0c25-4fbe-bc96-b1cb76097775.png">

then

<img width="372" alt="Screen Shot 2023-02-26 at 20 55 49" src="https://user-images.githubusercontent.com/950825/221454235-1b557dd8-90cf-4d9e-b1c9-8c1692a31c67.png">

---

I tried

```
$ ping 10.0.2.15
PING 10.0.2.15 (10.0.2.15): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
^C
--- 10.0.2.15 ping statistics ---
5 packets transmitted, 0 packets received, 100.0% packet loss
```

Which makes me think... the ip isn't even available. So is qemu self reporting 10.0.2.15 for itself but not outside the SSH from my Mac? 

If I try `vnc://localhost:5900` Screen Sharing immediately tells me the `Connection failed to “localhost”. Unable to communicate with “localhost”.  Make sure the remote computer is available and the firewall is not blocking screen sharing.` message seen above.

I'm probably confused about how qemu/vms work. So maybe this is a good moment for me to learn something new about linux. Thanks!

**Comment by maxzinkus** [comment]
> `alpine launch -s 22 #launch -p 5900`

Apologies if this is just from a misunderstanding, but did you run `alpine launch -s 22 -p 5900` or did you run it with the `#` comment in the command

**Comment by maxzinkus** [comment]
If you're able to `start` the VM without errors, ssh is working and so port 22 on that host is accessible. Within the VM, you could use `netstat` to double check that the port is listening on 5900, but it likely is given the logs you posted.

`qemu` sets up a 1:1 port forwarding (e.g. `ssh -p22 root@localhost` will pass through to the VM port 22), so `5900` on the host machine should be forwarded to the VM. Try VNC connecting to `localhost:5900` on the host machine.

**Comment by maxzinkus** [comment]
Also, ensure that nothing on your host machine is already binding port 5900. For example, if your host has a VNC server installed, that may be causing a silent failure somewhere.

**Comment by maxzinkus** [comment]
Apologies, I just saw your above that you tried that. Give me a moment to test a couple things.

**Comment by jdriselvato** [comment]
> Apologies, I just saw your above that you tried that. Give me a moment to test a couple things.

No worries,  Tried netstat and got this, if this helps:

```
netstat -na | grep "5900"
tcp4       0      0  *.5900                 *.*                    LISTEN  
```

It's bare enough to create more questions than answers for me.

**Comment by jdriselvato** [comment]
I've also tried changing the port for 5901, 5902, etc but didn't make a difference.

**Comment by maxzinkus** [comment]
`ping` will likely never work due to `qemu` passing through specific traffic. A good way to network-debug from the host machine is `ncat -v localhost port` to see if you're able to establish a TCP connection that gets passed through correctly.

**Comment by maxzinkus** [comment]
Can you try:
* setting the VNC port inside the VM (i.e. on `x11vnc`) to listen on `35900` (or any known-unused port)
* setting the `port` `config.yaml` entry to match
* VNCing from the host machine into `vnc://localhost:35900`

**Comment by maxzinkus** [comment]
Or do the first two steps and then `nc -v localhoust 35900` and share the error message that appears :)

**Comment by jdriselvato** [comment]
Sure I'll try that list. But just real quick I did this 
```
nc -v localhost 5900
nc: connectx to localhost port 5900 (tcp) failed: Connection refused
Connection to localhost port 5900 [tcp/rfb] succeeded!
```

**Comment by maxzinkus** [comment]
I also got this issue when testing with `nc -l 8080` inside the VM. What fixed it was `nc -lp 8080`. I think the BusyBox version of `nc` doesn't take the command line option for port unless you use `-p`.

**Comment by maxzinkus** [comment]
Run your `x11VNC` inside the VM, and try to connect to it with `nc -v` (verbose), and share that output.

**Comment by jdriselvato** [comment]
```
$ x11vnc -display :0 -rfbport 35900

(trimmed)
The VNC desktop is:      localhost:30000
26/02/2023 21:40:22 possible aliases:  localhost:35900, localhost::35900
PORT=35900
```

> Run your x11VNC inside the VM, and try to connect to it with nc -v (verbose), and share that output.

on host:
```
$ nc -v localhost 35900
nc: connectx to localhost port 35900 (tcp) failed: Connection refused
nc: connectx to localhost port 35900 (tcp) failed: Connection refused
```

but just because I see in the above `The VNC desktop is:      localhost:30000`

on host:
```
$ nc -v localhost 30000
nc: connectx to localhost port 30000 (tcp) failed: Connection refused
nc: connectx to localhost port 30000 (tcp) failed: Connection refused
```

if I run the same thing on the VM:

```
nc -v localhost 35900
localhost ([::1]:35900) open
```

**Comment by maxzinkus** [comment]
Try `port: "30000"`, out of curiosity.

**Comment by maxzinkus** [comment]
Also: does `nc` on the host fail immediately, or after ~30 seconds or more?

**Comment by jdriselvato** [comment]
<img width="444" alt="Screen Shot 2023-02-26 at 21 46 16" src="https://user-images.githubusercontent.com/950825/221461311-5bc3f6e7-76dd-4193-a894-d5b567fbfe44.png">

```
$ nc -v localhost 30000
nc: connectx to localhost port 30000 (tcp) failed: Connection refused
nc: connectx to localhost port 30000 (tcp) failed: Connection refused
```

**Comment by maxzinkus** [comment]
Also also: make sure to `alpine stop altruistic-minor && alpine start altruistic-minor` between any changes to `config.yaml`

**Comment by maxzinkus** [comment]
Also also also: [plug in your mac](https://user-images.githubusercontent.com/950825/221461311-5bc3f6e7-76dd-4193-a894-d5b567fbfe44.png) ;)

**Comment by jdriselvato** [comment]
> Also: does nc on the host fail immediately, or after ~30 seconds or more?

immediately. but aah. You're right, I forgot to reset the instance, still:

```
$ nc -v localhost 30000
nc: connectx to localhost port 30000 (tcp) failed: Connection refused
Connection to localhost port 30000 [tcp/*] succeeded!
```
So what's up with tcp failing but the `tcp/*` or `tcp/rfb` ([seen here](https://github.com/beringresearch/macpine/issues/75#issuecomment-1445588901)).

Just out of curiosity, I'm still seeing screen share immediately failing:

<img width="372" alt="Screen Shot 2023-02-26 at 21 50 13" src="https://user-images.githubusercontent.com/950825/221461765-734bf82f-671f-4d0c-84b5-a290ae1e7f6f.png">

**Comment by jdriselvato** [comment]
> Also: does nc on the host fail immediately, or after ~30 seconds or more?

This comment still had me curious. `$ nc -v 10.0.2.15 30000` seems to trying hard w/o a response after 30+ seconds.

**Comment by maxzinkus** [comment]
10.0.2.15 is probably something on your mac's local network. It's attempting to connect and getting no response, therefore timing out.

If you get an immediate fail, it likely means the connection received a response of TCP RST (reset i.e. close the connection).

Regarding the "success" then fail: the "success" message shows when `nc` see the port is open. I think it does this by starting the 3-way TCP handshake. However, shortly after, it must be getting an RST from qemu or alpine.

**Comment by maxzinkus** [comment]
I just independently came to the IPv6 conclusion, the saw your edit haha.

So it may have to do with how qemu is setting up the interface vs how x11vnc is expecting it to be bound (v6 vs v4).

Make sure you get the same thing as me, a successful connection with:
* `port: 30000` in `config.yaml`
* inside VM: `nc -vlp 30000`
* on host: `nc -v localhost 30000`

For me, the above succeeds and I can type "blah blah" on the host and hit enter, and see that text show up on the VM listener side.

**Comment by maxzinkus** [comment]
If all the above works, then it's 100% how `x11vnc` is binding the port... I think.

**Comment by jdriselvato** [comment]
It does work. 

Host:
```
$ nc -4v localhost 30000
Connection to localhost port 30000 [tcp/*] succeeded!
lol
lol2
```

VM:
```
$ nc -vlp 30000
listening on [::]:30000 ...
connect to [::ffff:10.0.2.15]:30000 from [::ffff:10.0.2.2]:51513 ([::ffff:10.0.2.2]:51513)
lol
lol2
```

> how x11vnc is binding the port

I'm not familiar enough with x11vnc to determine how to "bind" the port except through `-rfbport`. What you you suggesting? 

Thanks for looking over all this so far. Did you get vnc to work with macpine, btw?

**Comment by jdriselvato** [comment]
Ok, I think letting the vm sleep over night did some good. I reset the vm this morning, keeping port 30000 in `config.yaml` and starting `x11vnc -display :0 -rfbport 30000` like this.

I still see the `YOU ARE RUNNING X11VNC WITHOUT A PASSWORD!!` even after running `x11vnc -storepasswd`, reset the vm again. 


Try to connect with my vnc client and it hangs trying to get a display up with the following output:

```
26/02/2023 22:58:14 Got connection from client 10.0.2.2
26/02/2023 22:58:14   0 other clients
26/02/2023 22:58:14 Normal socket connection
26/02/2023 22:58:14 Disabled X server key autorepeat.
26/02/2023 22:58:14   to force back on run: 'xset r on' (3 times)
26/02/2023 22:58:14 incr accepted_client=1 for 10.0.2.2:52076  sock=11
26/02/2023 22:58:14 Client Protocol Version 3.3
26/02/2023 22:58:14 Protocol version sent 3.3, using 3.3
26/02/2023 22:58:14 created   xdamage object: 0x60002c
26/02/2023 22:58:17 rfbProcessClientInitMessage: client gone
26/02/2023 22:58:17 client_count: 0
26/02/2023 22:58:17 Restored X server key autorepeat to: 1
26/02/2023 22:58:17 connect_once: invalid password or early disconnect.  3
26/02/2023 22:58:17 connect_once: waiting for next connection.
26/02/2023 22:58:17 Client 10.0.2.2 gone
26/02/2023 22:58:17 Statistics             events    Transmit/ RawEquiv ( saved)
26/02/2023 22:58:17  TOTALS              :      0 |         0/        0 (  0.0%)
26/02/2023 22:58:17 Statistics             events    Received/ RawEquiv ( saved)
26/02/2023 22:58:17  TOTALS              :      0 |         0/        0 (  0.0%)
26/02/2023 22:58:17 destroyed xdamage object: 0x60002c
26/02/2023 22:58:17 Got connection from client 10.0.2.2
26/02/2023 22:58:17   0 other clients
26/02/2023 22:58:17 Normal socket connection
26/02/2023 22:58:17 Disabled X server key autorepeat.
26/02/2023 22:58:17   to force back on run: 'xset r on' (3 times)
26/02/2023 22:58:17 incr accepted_client=1 for 10.0.2.2:52077  sock=11
26/02/2023 22:58:17 Client Protocol Version 3.3
26/02/2023 22:58:17 Protocol version sent 3.3, using 3.3
26/02/2023 22:58:18 created   xdamage object: 0x60002d
26/02/2023 22:58:26 created selwin: 0x60002e
26/02/2023 22:58:26 called initialize_xfixes()
26/02/2023 22:58:33 cutbuffer_send: no send: uninitialized clients
26/02/2023 23:01:07 rfbProcessClientInitMessage: client gone
26/02/2023 23:01:07 client_count: 0
26/02/2023 23:01:07 Restored X server key autorepeat to: 1
26/02/2023 23:01:07 connect_once: invalid password or early disconnect.  3
26/02/2023 23:01:07 connect_once: waiting for next connection.
```

It does ask me for the password I previously set up. And it doesn't fail when bad auth. So at this point it must be my display manager that isn't setup fully. 

So the port isn't the issue any more! If anyone else runs into this I suggest ensuring you reset the vm/x11vnc when changing configuration.

**Comment by maxzinkus** [comment]
Excellent, I'm so glad resetting the VM worked things out. I had a zany experiment with local port binding and redirection using `socat` mostly typed out just now -- glad it won't be necessary!

All best.

**Comment by maxzinkus** [comment]
@jdriselvato close as resolved?
