### ISSUE TITLE
Hardening macpine VMs (functionality and documentation)

### ISSUE THREAD

**Issue by maxzinkus** [beringresearch/macpine#76]
In addition to adding security options, the documentation should be expanded to include any macpine-specific hardening instructions if a user's VM is expected to receive external network traffic/data or otherwise be used in a production environment.

Ones I can think of off the top of my head:
1. Documenting how to harden `config.yaml` once #70 is complete (done #90)
2. Placing restrictions around (root and other) ssh without breaking macpine (a la #67) (#73)
3. Signing and verifying `publish`'d/`import`'d VMs (ideally with [`age`](https://github.com/FiloSottile/age)) (#92)
4. Any `qemu`-related hardening tips or links (#97)

I can do 1-3, each in separate PRs. I can research 4, but if anyone (@idroz?) has expertise here their input would make that process faster.

**Comment by maxzinkus** [comment]
@idroz you can assign me here but this is a longer-term one :)

**Comment by idroz** [comment]
I'll research 4 - thanks as always!

**Comment by maxzinkus** [comment]
Item 1 is addressed by #90 :)

**Comment by maxzinkus** [comment]
Note: for hardening linux installs themselves, if hardening is mission-critical, [grsecurity](https://grsecurity.net) is probably the best (albeit non-free) approach.

**Comment by maxzinkus** [comment]
Unassigning self as 1-4 have PRs -- I don't think much more is needed for now, we can revisit this if it becomes a more direly needed/explicitly supported use-case.

**Comment by maxzinkus** [comment]
This can probably be closed out? :) @idroz
