### ISSUE TITLE
Allow mapping custom ports from host to guest

### ISSUE THREAD

**Issue by maxzinkus** [beringresearch/macpine#77]
As it stands, the `port` configuration maps ports 1:1 from host to guest. That is, adding `port: 1000` to `config.yaml` asks `qemu` to bind port 1000 on the host and forward it to 1000 on the guest.

It would be preferable for security to forward arbitrary unused high-range (>32000) ports to specific ports on the VM, or more generally to support something like this:

```yaml
port: 35022:22,35900:5900
```

To map (for example) `35022` on the host to `22` on the guest and `35900` on the host to `5900` on the guest.

**Comment by idroz** [comment]
Adding port mapping e.g. `port: 35022:22,35900:5900` is an elegant general solution.

Should be still support the basic defaults e.g. `ssh 23` to forward port 23 on VM to port 23 on host?

**Comment by maxzinkus** [comment]
Definitely agree. Perhaps if a plain port is specified, we can just do `host:port<->vm:port` to support newly-legacy configs, and then if a `port:port` mapping is specified we can ask qemu to do the custom mapping?

**Comment by maxzinkus** [comment]
Noting here as it's the linked issue: UDP forwarding is now available as well. Append `u` to a port in the `-p`/`port` string like `8080u` to forward UDP 8080 on the host to UDP 8080 on the guest.

UDP ports also support non-identity mappings. `8081:8082u` forwards UDP 8081 on the host to UDP 8082 on the guest.
