### ISSUE TITLE
VM clock is desynchronized after host system sleep

### ISSUE THREAD

**Issue by maxzinkus** [beringresearch/macpine#78]
I found that my VM was well into the future after my laptop slept for the night, despite multiple reboots with successful `hwclock -s`.

This makes sense to me as `hwclock -s` sets the system time from the RTC:

```man
BusyBox v1.36.0 (2023-02-08 20:53:50 UTC) multi-call binary.

Usage: hwclock [-swul] [--systz] [-f DEV]

Show or set hardware clock (RTC)

	-s	Set system time from RTC
	-w	Set RTC from system time
	--systz	Set in-kernel timezone, correct system time
		if RTC is kept in local time
	-f DEV	Use specified device (e.g. /dev/rtc2)
	-u	Assume RTC is kept in UTC
	-l	Assume RTC is kept in local time
		(if neither is given, read from /var/lib/hwclock/adjtime)
```

The RTC is likely wrong if the system was unaware of the sleep. I need to test this with another sufficiently long sleep period, but I think it would make more sense to:

* Re-sync the system clock from NTP (this requires `chronyd`, `ntpd`, or another NTP daemon to be configured in `alpine-setup`)
* `hwclock -w` to adjust the RTC based on the corrected system time

However, alpine doesn't have an NTP daemon by default -- it puts time management in the user's hands. Therefore by default, alpine supports the use case where a user may prefer to manually set the system time and then re-sync the RTC clock (?).

So, I think it makes the most sense to run `hwclock -w` during `Start` rather than `hwclock -s` -- and if the system clock is wrong, that's the user's problem, but at least the RTC isn't wrong with respect to the system clock.

@idroz let me know if this makes any sense or if I'm just missing something :)

**Comment by idroz** [comment]
Interesting re `-s` option. I haven't come across this issue, but intuitively `-w` sounds correct. Would be great if you could push a commit with this change :)

**Comment by maxzinkus** [comment]
Ok, tested this more thoroughly.

Rebooting my VM:
- system clock (`date`) says Feb 9th 2023 23:41:01 (lol)
- RTC says Feb 27th (correct) ... but 6 hours in the future (likely the amount of time the laptop slept?)
- `hwclock -s` did *not* update the system clock

Replaced `hwclock -s` in `Start` with `whoami` (no-op) and rebooted:
- system clock set to Feb 9 again
- RTC stayed the same

Steps required to fix:
- `chronyc makestep`: force an NTP update to fix the system time (`chronyd` is failing to update the time for some reason, but that's not macpine's fault)
- `hwclock -w1: update the RTC base on the newly corrected system time

**Comment by maxzinkus** [comment]
So: _if_ alpine linux was updating its time correctly (syncing NTP during/just after boot) or if the user is otherwise managing their system clock, a `hwclock -w` during boot will patch up the RTC.

However, as it stands (possibly due to how `runlevel default` lands in Alpine before `qemu` configures networking??) the NTP update fails.. so both the system clock and RTC end up wrong. But, at least, _consistently_ wrong.
