### ISSUE TITLE
Pass multiple VM names to `alpine delete`

### ISSUE THREAD

**Issue by idroz** [beringresearch/macpine#84]
Currently, macpine supports single vm operations. Passing a list of VMs to `alpine delete` is desirable.

**Comment by maxzinkus** [comment]
This could interact nicely with completion. In `zsh`, if you type `alpine delete name-*`, it could expand to all VMs with names starting with `name-`. If you used VM names to namespace your VMs, you could delete every VM associated with one topic all at once like `alpine delete project1-* [tab]`

**Comment by maxzinkus** [comment]
Also- if you add a helper to achieve this, it could be applied to `publish`, `edit`, `info`, `start`, and `stop` :)

**Comment by idroz** [comment]
# Addressed in #86
