### ISSUE TITLE
Add option for verifiable `publish`/`import`

### ISSUE THREAD

**Issue by maxzinkus** [beringresearch/macpine#92]
I plan to add this as an optional feature on `publish` & `import`.

`publish` creates a compressed archive, and `import` unpacks it into a `~/.macpine` VM directory.

Adding verifiability to this process would allow for:
* trustworthy sharing of imported VMs
* encrypted & authenticated backups of VMs

[`age`](https://github.com/FiloSottile/age) is a modern file-based authenticated-encryption tool written by a renown author in the cryptography community.

`age` can encrypt & authenticate:
* symmetrically, with a password
* asymmetrically, to an `age-keygen`-generated public key, or to an `ssh-keygen` ssh public key

Symmetric encryption can be used for secure backups or ease-of-use in verifiable sharing. Asymmetric encryption can be used to encrypt VMs to a specified recipient, including by using their publicly-listed GitHub SSH keys (example: https://github.com/maxzinkus.keys).

**Comment by maxzinkus** [comment]
@idroz check it out, when you have a chance :)

**Comment by maxzinkus** [comment]
TODO @maxzinkus: import `age` as a Go mod rather than system dep, and call it programmatically instead of using `exec`. Refer to https://github.com/FiloSottile/age/discussions/436

**Comment by maxzinkus** [comment]
@idroz once I have time to wrap this one up, maybe it could be time for v0.11 -- and maybe a round of hackernews / reddit / etc postings! I imagine the traffic is positive for your company and the new features are pretty fun and improve user QoL, so they could draw even more traction :)

**Comment by idroz** [comment]
I was thinking of doing a tightening up of the docs/adding some fun examples and doing the 0.11 release with features as they are now :) With the API stabilising and verifiable publish/import it may be time to put a roadmap together for 1.0 release?

Certainly hn/reddit awareness round would be good and I can put that together once 0.11 is out!

**Comment by maxzinkus** [comment]
#127 is ready for review!

**Comment by maxzinkus** [comment]
and- sounds good. I don't have any other API-level ideas or changes in the near term :)

**Comment by maxzinkus** [comment]
@idroz I messed up and accidentally merged this PR (#127) while trying to re-synchronize other changes to `main` into it. I tried to revert it (#134) but that seems to have made even more of a mess.
