### ISSUE TITLE
Add a `restart` instance command

### ISSUE THREAD

**Issue by jdriselvato** [beringresearch/macpine#94]
Instead of having to write `alpine stop <instance> && alpine start <instance>` or creating an alias for it for your own system, a simple `alpine restart <instance>` would be a great addition.

I suppose there's a topic to debate on wording:

- restart
- reset
- reboot

**Comment by idroz** [comment]
I think that could be handy. I suggest `alpine restart`.

**Comment by maxzinkus** [comment]
Potential `good-first-issue` tag on this one?

**Comment by maxzinkus** [comment]
I can pick this up after #112 lands, and I'll match the multiple-vm-name handling that PR adds :)
